version: 0.2
phases:
    pre_build:
        commands:
            - echo Logging into ECR
            - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
            - BUILD_TAG=$(date +%Y%m%d%H%M)
            - echo setting container tag $BUILD_TAG
    build:
        commands:
            - echo Build started on $(date +%Y %m %d %H:%M:$S)
            - echo Building the Docker image...
            - cd applications/server
            - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
            - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
            - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
            - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$BUILD_TAG 
            - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER 
    post_build:
        commands:
            - echo pushing image on $(date +%Y %m %d %H:%M:$S) 
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$BUILD_TAG
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER
            - cd src
            - TASK_ARN=$(aws ecs register-task-definition --family $ECS_TASKDEF_FAMILY --cli-input-json file://taskdef.json | jq -r ".taskDefinition.taskDefinitionArn")
            - echo $TASK_ARN
            - ./makeappspec.js _appspec.json $TASK_ARN > appspec.json
artifacts:
    files:
        - 'appspec.json'
        - 'taskdef.json'
    base-directory: applications/server/src
    name: /builds/$CODEBUILD_BUILD_NUMBER.zip